export const ERR_TYPE_SIGN_IN = 'ERR_SIGN_IN';
export const ERR_TYPE_GET_AUTHORIZATION_CODE = 'ERR_GET_AUTHORIZATION_CODE';
export const ERR_TYPE_GOOGLE_OAUTH = 'ERR_GOOGLE_OAUTH';
export const ERR_TYPE_FIREBASE_SIGN_IN = 'ERR_FIREBASE_SIGN_IN';